// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAiiIdau62O1aX0-tcP1Z4kbVrzRIdZ9jg',
    appId: '1:181893875604:web:355e58dab917f4f3747181',
    messagingSenderId: '181893875604',
    projectId: 'fir-1b8b4',
    authDomain: 'fir-1b8b4.firebaseapp.com',
    storageBucket: 'fir-1b8b4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuabbocufUmJsl6dW0IjC1YzUUPrz57as',
    appId: '1:181893875604:android:a6d8e99ed1b9ff73747181',
    messagingSenderId: '181893875604',
    projectId: 'fir-1b8b4',
    storageBucket: 'fir-1b8b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAvcPWPYLmC5gOpQE3-XagOl7wzwN1WZM',
    appId: '1:181893875604:ios:a37e6ba471d4b73c747181',
    messagingSenderId: '181893875604',
    projectId: 'fir-1b8b4',
    storageBucket: 'fir-1b8b4.appspot.com',
    iosBundleId: 'com.example.fharmony',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAvcPWPYLmC5gOpQE3-XagOl7wzwN1WZM',
    appId: '1:181893875604:ios:a37e6ba471d4b73c747181',
    messagingSenderId: '181893875604',
    projectId: 'fir-1b8b4',
    storageBucket: 'fir-1b8b4.appspot.com',
    iosBundleId: 'com.example.fharmony',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAiiIdau62O1aX0-tcP1Z4kbVrzRIdZ9jg',
    appId: '1:181893875604:web:42bc10e3c5cf6aeb747181',
    messagingSenderId: '181893875604',
    projectId: 'fir-1b8b4',
    authDomain: 'fir-1b8b4.firebaseapp.com',
    storageBucket: 'fir-1b8b4.appspot.com',
  );

}